default_stages: [pre-commit]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.1
    hooks:
      - id: commitizen
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      # - id: terraform-validate
      # - id: tflint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-merge-conflict
      - id: mixed-line-ending
